name: Train Model with MLflow
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      # a. Setup Job
      - name: Set up job
        uses: actions/checkout@v3

      # c. Setup Python 3.12.7
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      # d. Check Env
      - name: Verify Python
        run: |
          python --version
          pip --version

      # e. Install dependencies
      - name: Install dependencies
        run: |
          pip install -r MLProject/conda.yaml
          pip install mlflow

      # f. Run MLflow project
      - name: Execute MLflow Project
        run: |
          mlflow run MLProject/ --experiment-name="CI_Experiment"

      # g. Get latest run_id (Opsional untuk Basic)
      - name: Extract Run ID
        id: get-run-id
        run: |
          RUN_ID=$(mlflow runs list --experiment-id 1 | head -3 | tail -1 | awk '{print $NF}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_OUTPUT
        shell: bash